services:
  - type: pserv
    name: ollama-service
    runtime: docker
    plan: free
    dockerImage: ollama/ollama:latest
    envVars:
      - key: OLLAMA_HOST
        value: 0.0.0.0
    autoDeploy: false
